### ISSUE TITLE
엔티티 상속관계 설정

### ISSUE THREAD

**Issue by seokbeom00** [NOWSOPT-CDSP-WEB-7/YES24-WEB-SERVER#1]
## 📝  To-do

- [x] Show 테이블에 상속전략 추가
- [x] 상속에 따른 RunShow @ID 컬럼 제거
- [x] Show 테이블 @ID 컬럼명 변경
- [x] Booking 테이블 오타 수정
