### ISSUE TITLE
홈화면 메인 캐러셀

### ISSUE THREAD

**Issue by seokbeom00** [NOWSOPT-CDSP-WEB-7/YES24-WEB-SERVER#3]
## 📌  Feature Issue
* 홈화면 메인 캐러셀 구현

## 📝  To-do

- [x] 메인 캐러셀 응답 DTO 구현
- [x] 메인 캐러셀 Controller 구현
- [x] 메인 캐러셀 Service 구현
- [x] 메인 캐러셀 Reposiroty 구현
