### ISSUE TITLE
검색창 검색 결과 API

### ISSUE THREAD

**Issue by seokbeom00** [NOWSOPT-CDSP-WEB-7/YES24-WEB-SERVER#6]
## 📌  Feature Issue
검색어에 따른 상영정보 리스트 반환 API 입니다.

## 📝  To-do
- [x] runshow/search 컨트롤러 구현
- [x] runshow/search 서비스 구현
- [x] runshow/search 응답 Dto 구현
- [x] runshow/search 레포지토리 구현
